"""
LangGraph pipeline that orchestrates the full AI Data Analyst workflow.

Graph topology:

    START
      │
      ▼
    intent_classifier ──► [conditional routing]
      │                        │                    │
      ▼                        ▼                    ▼
    sql_generator          rag_search         response_generator ──► END
      │                        │
      ▼                        │
    execute_query              │
      │                        │
      ▼                        │
    chart_recommender          │
      │            │           │
      ▼            ▼           │
    chart_gen   response_gen ◄─┘
      │            │
      ▼            │
    response_gen ◄─┘
      │
      ▼
     END
"""
import logging
from typing import TypedDict, Optional

from langgraph.graph import StateGraph, START, END

from app.langgraph.nodes.intent_classifier import classify_intent
from app.langgraph.nodes.sql_generator import generate_sql
from app.langgraph.nodes.chart_recommender import recommend_chart
from app.langgraph.nodes.response_generator import generate_response
from app.database.query_executor import execute_sql
from app.charts.chart_generator import generate_chart
from app.rag.rag_query import search_and_answer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# State schema
# ---------------------------------------------------------------------------

class AnalystState(TypedDict, total=False):
    question: str
    intent: str
    db_schema: dict
    sql_query: str
    sql_explanation: str
    query_result: list
    query_columns: list
    chart_type: str
    chart_data: dict
    chart_image: str
    x_column: Optional[str]
    y_column: Optional[str]
    label_column: Optional[str]
    text_summary: str
    rag_context: str
    final_response: dict
    error: str


# ---------------------------------------------------------------------------
# Thin wrapper nodes (delegate to domain modules)
# ---------------------------------------------------------------------------

def execute_query_node(state: dict) -> dict:
    """Execute the SQL generated by sql_generator against PostgreSQL."""
    if state.get("error"):
        return {}

    sql = state.get("sql_query", "")
    if not sql:
        return {"error": "No SQL query was generated"}

    try:
        rows, columns = execute_sql(sql)
        return {"query_result": rows, "query_columns": columns}
    except Exception as e:
        logger.exception("Query execution failed")
        return {"error": f"Query execution failed: {e}"}


def generate_chart_node(state: dict) -> dict:
    """Render a matplotlib chart and return base64 image + JSON data."""
    if state.get("error"):
        return {}

    chart_type = state.get("chart_type", "table")
    if chart_type in ("text", "table"):
        return {}

    query_result = state.get("query_result", [])
    if not query_result:
        return {}

    try:
        chart_data, chart_image = generate_chart(
            data=query_result,
            chart_type=chart_type,
            x_column=state.get("x_column"),
            y_column=state.get("y_column"),
            label_column=state.get("label_column"),
            title=state.get("question", ""),
        )
        return {"chart_data": chart_data, "chart_image": chart_image}
    except Exception as e:
        logger.exception("Chart generation failed, falling back to table")
        return {"chart_type": "table"}


def rag_search_node(state: dict) -> dict:
    """Retrieve relevant document chunks for a RAG query."""
    try:
        context = search_and_answer(state["question"])
        return {"rag_context": context}
    except Exception as e:
        logger.exception("RAG search failed")
        return {"rag_context": "", "error": f"Document search failed: {e}"}


# ---------------------------------------------------------------------------
# Routing functions
# ---------------------------------------------------------------------------

def _route_by_intent(state: dict) -> str:
    if state.get("error"):
        return "response_generator"
    intent = state.get("intent", "general_question")
    if intent == "database_query":
        return "sql_generator"
    if intent == "rag_query":
        return "rag_search"
    return "response_generator"


def _route_after_chart_rec(state: dict) -> str:
    if state.get("error"):
        return "response_generator"
    if state.get("chart_type") in ("bar", "line", "pie"):
        return "chart_generator"
    return "response_generator"


# ---------------------------------------------------------------------------
# Graph construction
# ---------------------------------------------------------------------------

def build_graph():
    """Build and compile the LangGraph analysis pipeline."""
    builder = StateGraph(AnalystState)

    builder.add_node("intent_classifier", classify_intent)
    builder.add_node("sql_generator", generate_sql)
    builder.add_node("execute_query", execute_query_node)
    builder.add_node("chart_recommender", recommend_chart)
    builder.add_node("chart_generator", generate_chart_node)
    builder.add_node("rag_search", rag_search_node)
    builder.add_node("response_generator", generate_response)

    builder.add_edge(START, "intent_classifier")

    builder.add_conditional_edges(
        "intent_classifier",
        _route_by_intent,
        {
            "sql_generator": "sql_generator",
            "rag_search": "rag_search",
            "response_generator": "response_generator",
        },
    )

    builder.add_edge("sql_generator", "execute_query")
    builder.add_edge("execute_query", "chart_recommender")

    builder.add_conditional_edges(
        "chart_recommender",
        _route_after_chart_rec,
        {
            "chart_generator": "chart_generator",
            "response_generator": "response_generator",
        },
    )

    builder.add_edge("chart_generator", "response_generator")
    builder.add_edge("rag_search", "response_generator")
    builder.add_edge("response_generator", END)

    graph = builder.compile()
    logger.info("LangGraph analysis pipeline compiled successfully")
    return graph


# Singleton accessor
_graph = None


def get_graph():
    """Return (and lazily build) the compiled LangGraph pipeline."""
    global _graph
    if _graph is None:
        _graph = build_graph()
    return _graph
